### ISSUE TITLE
updateConfig does nothing if all components use `providers: [NGXLogger]`

### ISSUE THREAD

**Issue by ghiscoding** [dbfannin/ngx-logger#103]
Hello, I'm starting to use your logger which is a nice tool, however I'm having this issue where if I try to use this piece of code
```ts
this.logger.updateConfig({ level: NgxLoggerLevel.INFO });
```
It is not reflected in any of my components, I found that it's because of the 
```ts
@Component({
  templateUrl: './template.html',
  providers: [NGXLogger],
})
```
But I'm wondering, why do we need the `providers` for? I know it's for transient (non-singleton), but why do we need a transient logger service? Anyhow, using the `updateConfig` doesn't seem to stick with transient. What would be the effect if I remove the `providers` of `ngx-logger` in all my components?

Also note that I'm using an older version `2.2.4` because our project is still under Angular 5.

**Comment by dbfannin** [comment]
@ghiscoding, thanks for using the logger!  I did not pull down and test version 2.2.4, but I did test with the latest version and providing the logger at the component level does respect the config changes. 

My first though is that since you are providing the logger at the component level, that instance is only used for that component. So, other components using the logger wouldn't have their configs updated. Unless you need a new instance for each component, I would suggest using module level registration.

What is your use case for registering the logger at the component level instead of at the module level?

**Comment by ghiscoding** [comment]
@dbfannin 
Thanks for replying

> I would suggest using module level registration.

Do you mean removing the `providers` in each component? That is what I would like to do that, but I was wondering why the `README` seems to put more focus on using it with the `providers`. If you say that it's all good without it, then I will do that. Thanks

**Comment by dbfannin** [comment]
@ghiscoding, Yikes. You found a big flaw in our README. Thank you thank you thank you. I'm very sorry for the confusion there. We do NOT suggest using component level providers. I'm surprised no one else has pointed this out yet.

Move your registration to the module level, and remove it from the components. I will update the documentation right now.

**Comment by dbfannin** [comment]
Btw. you should be importing the `LoggerModule` into your module, not NGXLogger directly.

**Comment by dbfannin** [comment]
FYI. Readme has been updated. Good catch @ghiscoding!

**Comment by ghiscoding** [comment]
@dbfannin 
Just FYI, I believe the `README` was changed since this issue #1 

Thanks for clearing the confusion, I assume I can close the issue since you update the `README` 😉 
Have a nice day ☀️
