### ISSUE TITLE
Feature request: add HttpClient option responseType: 'text'

### ISSUE THREAD

**Issue by asussitz** [dbfannin/ngx-logger#108]
Hi there,
I want to use ngx-logger with logstash's http input plugin. The default response of logstash is non-JSON string "ok" and results into the following Exception: 

> SyntaxError: Unexpected token o in JSON at position 0 at JSON.parse (<anonymous>) at XMLHttpRequest.onLoad

Maybe it would be better if we could preconfigure httpOptions?

**Comment by kaflake** [comment]
Hi,
I have the same problem. Is there an workaround. Logging still working but I don't want to get this error.

**Comment by dbfannin** [comment]
@asussitz, @kaflake Sorry it's taken me so long to get to this! In order to keep from making a breaking change, I've added httpResponseType as a config option that you can set. This is available in `ngx-logger@3.3.12`. 

Could one of you please pull down the latest version and verify that it is working as expected? If so, please close out this issue. Thanks!

**Comment by kaflake** [comment]
Fix is working for me. Thank you for your fast help.

**Comment by dbfannin** [comment]
@kaflake thank you for verifying this for me! Closing this issue.

**Comment by asussitz** [comment]
@dbfannin thank you! :)
