### ISSUE TITLE
Dinamically change serverLoggingUrl accordingto user

### ISSUE THREAD

**Issue by eugenioghio** [dbfannin/ngx-logger#125]
Is there a way to change the serverLoggingUrl at runtime?
If no, then I suggest it as a **critically important** feature to be added.
I have different classes of user that need to log to their own servers, for reasons.
Being able to update the http params is not enough

**Comment by dbfannin** [comment]
@eugenioghio, This is possible by using the `updateConfig` method on the logger. This does update the entire config for that logger.

For your scenario, instead of updated the config every time you want to make a request to a new server, you might want to look into creating custom loggers for each unique use case. you could have multiple (or a single) service in your app that manages the loggers. see `CustomNGXLoggerService` in the docs. I would expect it to look something like this though

```
export class MyLoggersService {
  readonly userLogger: NGXLogger;
  readonly customerLogger: NGXLogger;

  constructor(customLogger: CustomNGXLoggerService) {
    this.userLogger = customLogger.create({ level: NgxLoggerLevel.ERROR, ... });
    this.customerLogger = customLogger.create({ level: NgxLoggerLevel.ERROR, ... });
  }
}
```

**Comment by dbfannin** [comment]
Please check to docs for details on how to use `updateConfig` and the `CustomNGXLoggerService `.
