### ISSUE TITLE
Add timestamp to logs send to server

### ISSUE THREAD

**Issue by fsteinke** [dbfannin/ngx-logger#14]
It would be very helpful for us, if the json object that contains the log and is send to the server would already contain the timestamp as well. Or are there any reasons, that the time shouldn't be send to the logging server?

**Comment by dbfannin** [comment]
@fsteinke, timestamps taken on browsers can be inaccurate for multiple reasons. Or, if your browser time is not inaccurate, there is a possibility that your server's timestampis. If you are trying to track a clientside error, and relate it to an error that occurred on the server, using timestamps generated on 2 different machines can make sometimes make that extremely difficult. 

However, I've added it to the payload that is being sent to the server (v0.2.2). If you feel it's valuable, you can use it, otherwise, it can be ignored. If you do decide to use it, I would still log the server's time as well, so you can compare times against that.

Hope this helps. Thanks for using the logger!
