### ISSUE TITLE
Can't resolve 'ngx-logger/logger.service' error 

### ISSUE THREAD

**Issue by leo6104** [dbfannin/ngx-logger#16]
![](https://i.imgur.com/wOcsyTn.png)

the root cause is that index.d.ts 
```typescript
export { NGXLoggerMock } from './logger.service.mock';
export { NGXLogger, LoggerConfig } from './logger.service';
```
index.d.ts export NGXLogger from logger.service.(ts/js). However, there is no 'logger.service.js' file in npm project.

`ng s` command error 
```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'ngx-logger/logger.service' in '~/mapia_ng2/src/app'
resolve 'ngx-logger/logger.service' in '~/mapia_ng2/src/app'
  Parsed request is a module
  using description file: ~/mapia_ng2/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: ~/mapia_ng2/package.json (relative path: ./src/app)
    resolve as module
      ~/mapia_ng2/src/app/node_modules doesn't exist or is not a directory
      ~/mapia_ng2/src/node_modules doesn't exist or is not a directory
      ~/node_modules doesn't exist or is not a directory
      looking for modules in ~/mapia_ng2/node_modules
        using description file: ~/mapia_ng2/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: ~/mapia_ng2/package.json (relative path: ./node_modules)
          using description file: ~/mapia_ng2/node_modules/ngx-logger/package.json (relative path: ./logger.service)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              ~/mapia_ng2/node_modules/ngx-logger/logger.service doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              ~/mapia_ng2/node_modules/ngx-logger/logger.service.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              ~/mapia_ng2/node_modules/ngx-logger/logger.service.js doesn't exist
            as directory
              ~/mapia_ng2/node_modules/ngx-logger/logger.service doesn't exist
```

**Comment by leo6104** [comment]
index.ts would be exporting like below. (for import NgxLoggerLevel) 

export * from './logger.service.mock';
export * from './logger.service';

**Comment by leo6104** [comment]
gulp rollup give some message 
```
'@angular/common/http' is imported by build/index.js, but could not be resolved – treating it as an external dependency
'rxjs/add/operator/map' is imported by build/logger.service.js, but could not be resolved – treating it as an external dependency
'rxjs/add/operator/catch' is imported by build/logger.service.js, but could not be resolved – treating it as an external dependency
'@angular/common/http' is imported by build/logger.service.js, but could not be resolved – treating it as an external dependency
```

I think gulpfile.js would be better to change like below 

gulp step 5
```
gulp.task('rollup', function () {
  return gulp.src(`${buildFolder}/**/*.js`)
  // transform the files here.
    .pipe(rollup({
      // any option supported by Rollup can be set here.
      entry: `${buildFolder}/index.js`,
      external: [
        '@angular/core',
        '@angular/common',
        '@angular/common/http',
        'rxjs/add/operator/map',
        'rxjs/add/operator/catch',
        'moment'
      ],
      format: 'es'
    }))
    .pipe(gulp.dest(distFolder));
});
```

gulp step 6 
```
gulp.task('copy:build', function () {
  return gulp.src([`${buildFolder}/**/*`])
    .pipe(gulp.dest(distFolder));
});
```

Is there reason to creating flat ES module?

**Comment by dbfannin** [comment]
@leo6104, this library was build using https://github.com/jvandemo/generator-angular2-library which is a very handy tool. The generator has been updated several times since the creation of this project, so it might be getting close to time to rebuild the shell off of the generator. 

I'm not sure I really like the idea of removing the `!${buildFolder}/**/*.js` in step 6. Many IDEs will compile your typescript for you in which case it could cause headaches in managing this when it is time to build. Just curious as to why you think this would be helpful?

Adding the additional lines to step 5 should remove the Warnings logged by rollup, but shouldn't change the output at all.

**Comment by dbfannin** [comment]
Also, I think you assumption about there being an issue with it not resolving logger.service.js is a red herring. That will resolve to logger.service.d.ts because typescript is looking for typings to resolve. This is the same file structure that was in older versions of the logger where you were not receiving this error. (see image below:)
![screen shot 2017-09-15 at 7 55 48 am](https://user-images.githubusercontent.com/15847407/30483145-67c77ccc-99eb-11e7-8216-b7f94a82de51.png)

**Comment by leo6104** [comment]
@dbfannin Sorry for confusing you. 
I tried to reproduce this issue and then i could found it was my mistake of import. 
I did `import {NgxLoggerLevel} from 'ngx-logger/logger.service';` in my project. 
I resolve the error with `import {NgxLoggerLevel} from 'ngx-logger';`

Thank you for advising me.

**Comment by dbfannin** [comment]
Glad to hear it was a non-issue!
