### ISSUE TITLE
Cannot log FormGroup with innner FormGroup

### ISSUE THREAD

**Issue by laurent-thiebaud-gisaia** [dbfannin/ngx-logger#177]
Hi,

When I try to log a FormGroup instance like I usually do it with `console.log`, it returns me:
`The provided "message" value could not be parsed with JSON.stringify().`

After some tests:
`this.logger.info(new FormGroup({}));` is OK
`this.logger.info(new FormGroup({ sub: new FormGroup({}) }));` is KO

I guess this is some circular link between both FormGroups.

How can I avoid this?

Thx.

**Comment by bmtheo** [comment]
Here is the repro (https://stackblitz.com/edit/ngx-logger-circular-dep?file=src/app/app.component.ts), it is caused by this line

`message = NGXLoggerUtils.prepareMessage(message);`

I think this line is not really useful as we can send this straight to the console.log call or in the logOnServer function

**Comment by bmtheo** [comment]
The PR #223 should fix this issue

Please bear in mind that this error will still occur when using serverLogging as we are still using JSON.stringify to flatten the data into a string
