### ISSUE TITLE
Allow log level to be set within a module tree

### ISSUE THREAD

**Issue by muuvmuuv** [dbfannin/ngx-logger#204]
I would like to set the log level in my UI section to debug and everywhere else leave it on info. Is that possible atm? I think this could be done with injection tokens.

```ts
  providers: [
    {
      provide: LOG_LEVEL,
      useValue: LogLevel.DEBUG,
    },
  ],
```

**Comment by bmtheo** [comment]
Yes you can do that with the service itself, instead of providing the logLevel you can directly provide the service and then change the logLevel. The level will only change on the current instance of the service
Here is a working example : https://stackblitz.com/edit/ngx-logger-level-only-on-instance?file=src/app/app.component.ts
