### ISSUE TITLE
File/Line numbers?

### ISSUE THREAD

**Issue by sam-lex** [dbfannin/ngx-logger#21]
Currently the line numbers are lost: showing as `index.js` which points to where the console.log is being called
<img width="527" alt="screen shot 2017-09-16 at 3 16 58 pm" src="https://user-images.githubusercontent.com/16538547/30514766-263366ba-9af2-11e7-9ec9-eb8b59924c07.png">

This picture shows as `vendor.bundle.js` because I had `--sourcemap=false` on.

I did managed to get it to show the "correct" file/line like so:
<img width="532" alt="screen shot 2017-09-16 at 3 32 55 pm" src="https://user-images.githubusercontent.com/16538547/30514896-b5aa0f36-9af4-11e7-8037-5bb7bbd98cef.png">

But with a major downside, and that is having to make the call with extra `()`.
```typescript
// before
this.logger.trace('Hi there');
// after
this.logger.trace('Hi there')();
// changes
this.logger.trace('Hi there') // returns a "formatted console.log function"
// so executing right after would result into showing the right file/line number
```

To avoid breaking the api, we could set a flag to make it either log directly or return a function.  
I can't think of a "pretty" way of doing this though. Any thoughts?

**Comment by sam-lex** [comment]
have a look, I'll make a pull request if this is ok:  
https://github.com/sam-lex/ngx-logger/commit/0f1a8325950bf12929ecc40f5ca5ac69ab81b690

Changes:  
+ added `logImmediately` option, defaults to `true`  
+ `_log` now returns a `formatted console log` function

Usage:
```typescript
// Same as before, no changes
this.logger.trace('Hi there'); // Hi there                   index.js ...

// or .. set 'logImmediately' to false:
LoggerModule.forRoot({
  serverLogLevel: NgxLoggerLevel.TRACE,
  level: NgxLoggerLevel.TRACE,
  logImmediately: false
}),
// and add '()' when using
this.logger.trace('Hi there')(); // Hi there                app.component.ts ...
// if 'logImmediately' is not defined or set to true.
// It will log twice. Once inside the logger function, and once on the 'caller' side.
```

`_logIE(..)` part is not implemented yet. For now, it just returns an empty function `() => {}` at the end.

Not sure if it's worth the trouble though, adding '()' can be quite annoying .. and ugly.

**Comment by avatsaev** [comment]
This is very bad, pretty much makes the logger useless, too bad.

**Comment by avatsaev** [comment]
so, was this merged?

**Comment by sam-lex** [comment]
nope, not yet ...  
I've been using this "new way" of adding extra `()`. Works ok, but many times I log and forget the extra `()`, so I go and test my app and keep thinking why my log doesn't get called, then I keep looking at different places where I might have messed up, until I realized I forgot the `()`.

So instead of really helping, it could hinder your development (sometimes).

Tried looking at how other loggers do it, they don't (without some sort of performance implications - like using the `Error().stack` and parsing it somehow).

**Comment by avatsaev** [comment]
yep I just tried by packaging your fork, it works but it feels hacky with the extra ().

Without showing the file and line number it's pretty difficult to debug.

**Comment by dbfannin** [comment]
@sam-lex, I'm not sure I like returning a function for this non `logImmediately` function. However, I can see the benefit in being able to have the line number from where the logger was called.

Here are my thoughts:
1. Most users are probably writing their log messages so that they are unique and can be easily found using the logged message alone. This is a pretty standard best practice for logging.

1. Mixing the intent of the logging methods doesn't follow the SOLID practices. 


So how do we extend the logger with these things in mind:
1. We can't penalize the majority of the users
1. We need to be explicit in how the logger works without obscurity (when possible)
1. We should do our best to be "SOLID". 

One idea would be to have a function that builds and returns the arguments that are passed to console.log. You could use the logger to build out the arguments, but call console.log in your own file:
```
const args = this.logger.getArgs(NgxLoggerLevel.ERROR, 'My error message', {more: 'stuff here'});
console.log(...args)
```

getArgs would return 
```
[
    `%c2017-09-19T13:00:56Z [Error] %cMy error message`, 
    `color:red`, 
    `color:black`, 
    {more: 'stuff here'}
]
```

I realize this would be more code to type than adding () at the end of the logger call, but this new method could be leveraged by the existing logging methods and it would have a single purpose. Also, when using it this way, you wouldn't accidentally forget to add the (), but instead it would be very clear what arguments the method needs to complete its task.

Your thoughts?

**Comment by sam-lex** [comment]
Yeah, adding `()` is really not ideal. Creating a `getArgs` function to later call it yourself with `console.log` does make it clear and easy to understand what's happening, but I think it's way too much code to make it worth.

Since my javascript knowledge is very limited, I'll have to research more before I can suggest another solution.

One idea that I got, but have no clue how to do it, or if it's even possible:  

Override the `console.log` method. (yes this sounds terrible, but hold on..)  
Just to make it call the `_logOnServer` method.  
then, call the original console.log.

Reason, it's possible to return a "formatted" console.log.  
With slight modifications we could change:  
`debug(...args)` to `debug = (formatted console log function)`  
so we could use it like so:  
`this.logger.debug('hi there');`

which is perfect except that it won't log to the server.

So if it's possible to somehow chain the `_logOnServer` to console.log automatically, or override it at instance level so that it won't affect the normal console, then we can get this done beautifully.

**Comment by leo6104** [comment]
I found some stack overflow documents (related to stack tract / caller function tracking) 
https://stackoverflow.com/questions/280389/how-do-you-find-out-the-caller-function-in-javascript
Maybe, it can be trace caller function by `arguments.callee.caller.caller`

**Comment by dbfannin** [comment]
@sam-lex, I don't think we should go the route of overriding console.log. It would never be a good idea to do something like this. Since console is shared globally, it would not just make the change for your code, but also for every other module that you've imported. It could have some pretty gnarly side effects.

@leo6104, It appears that arguments.callee.caller is deprecated.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee

**Comment by leo6104** [comment]
@dbfannin  :sob:  Okay, i try to find another way. Thank you for giving updated information. (Korean references are not up-to-date translations.)

**Comment by sam-lex** [comment]
not on my side, I've been using my own work-around version, but is not really useful to me anymore, it's taking a long time to build my angular project. https://github.com/angular/angular-cli/issues/5775#issuecomment-310637159

so with `ng serve --sourcemap=false`, is just shows `main.bundle.js: ...line number`

**Comment by abielikesu** [comment]
Hi Guys,

@dbfannin your idea about the args is great, and it actually has many more use cases. It resembles my favourite GoLang logging library:  https://github.com/Sirupsen/logrus

The syntax I normally use goes like this:
`
log.WithFields(log.Fields{
    "module": "Animals",
    "animal": "walrus",
 }).Info("A walrus appears")
`

**Comment by StAn187** [comment]
I'm currently testing some logging libraries and [loglevel](https://github.com/pimterry/loglevel) was the only one that solves the "File/Line numbers" problem. Maybe it can be used as an inspiration ;)

**Comment by dbfannin** [comment]
@StAn187, the library loglevel has a slightly different use case. They do not format or modify the console text at all, and they also don't support logging on serverside. Because of this, they can bind their methods to console. Unfortunately, we can't do that.


However, since we're still having a lot of pull for this feature, I've made some changes so that we can log the filename and line number along with the logs. After #56, this feature should be supported!

**Comment by sellmic** [comment]
loglevel has a plugin for server side logging
https://github.com/kutuluk/loglevel-plugin-remote

**Comment by dbfannin** [comment]
filename:line number is now supported in ngx-logger@2.2.0. Hopefully this helps!

**Comment by JavierFuentes** [comment]
Hi @dbfannin , I just upgraded one project _from_ __Angular CLI 1.7.4 with ngx-logger: ^2.2.4__ _to_ __Angular CLI 6.0.3 with ngx-logger ^3.0.0-rc1__ and filename:linenumber do now reference to __index.js__ all the time when i run `ng serve` from command line...

Example:
`2018-05-20T18:36:33.722Z TRACE [main.js:4703] mergeFields        ngx-logger.js:386`

**Comment by TeXnicians** [comment]
@JavierFuentes have you solved this `main.js` issue?

**Comment by dbfannin** [comment]
@TeXnicians follow #69 for updates.

**Comment by silentsnooc** [comment]
For me the line numbers work if I add `--eval-source-map` e.g.:

```
ng serve --host 0.0.0.0 --ssl --port 4200 --eval-source-map
```

**Comment by Zenguro** [comment]
> For me the line numbers work if I add `--eval-source-map` e.g.:
> 
> ```
> ng serve --host 0.0.0.0 --ssl --port 4200 --eval-source-map
> ```

Doesn't seem to work in the latest Angular version 7.2.x

**Comment by silentsnooc** [comment]
@Zenguro I am on 7.2.2 - must be something else.

**Comment by silentsnooc** [comment]
Back again. Now using Angular 8. The option is still deprecated but `ng serve --eval-source-map` also still works.

**Comment by Yang-LiYing** [comment]
before resolved, this is request on the log
```
{
  "message": "this is error",
  "additional": [],
  "level": 5,
  "timestamp": "2020-04-14T06:52:46.526Z",
  "fileName": "my.service.ts?",
  "lineNumber": "25"
}
```
after
```
{
  "message": "this is error",
  "additional": [],
  "level": 5,
  "timestamp": "2020-04-14T07:29:21.384Z",
  "fileName": "app.component.ts?",
  "lineNumber": "38"
}
```
I'm resolved by this way.
`providers: [
        { provide: LOG_PROVIDER, useClass: NGXLogger, multi: false }
 ]`
and inject to any use
`@Inject(LOG_PROVIDER)log: LogInterface,`
hope useful
