### ISSUE TITLE
Add DatePipe to LoggerModule forRoot() and forChild()

### ISSUE THREAD

**Issue by Gromov-Roman** [dbfannin/ngx-logger#218]
It is needed for Angular projects, where using only LoggerModule.forChild().providers

**Comment by bmtheo** [comment]
Any chance you give us a repro, I'm not quite sure I understand why the DatePipe is needed in the module

**Comment by qortex** [comment]
@bmtheo That's because of #160 & subsequent where we introduced the `DatePipe` to customize timestamps.

I'm not familiar with `forRoot` & `forChild` though. I added `DatePipe` to the `providers` for `LoggerModule`. @Gromov-Roman , do you mean it shoud also be added to `providers` in `forRoot` and `forChild`, or should it be imported?

See https://github.com/dbfannin/ngx-logger/blob/master/src/lib/logger.module.ts

**Comment by bmtheo** [comment]
Yes DatePipe was added thus fixing the issue
