### ISSUE TITLE
Turn Off Logging for Particular Component

### ISSUE THREAD

**Issue by logavdm** [dbfannin/ngx-logger#30]
Hi,
   1. Option like turn off logger for particular component that will be very use full for trace the logs.
   2. if unique key for different session will be easy to manage logs.
   3.logs shows like index.html and bundle.js that cannot be showed like component.ts like exactly please 
      improve this.
Please consider my point please add this features to package.

**Comment by dbfannin** [comment]
@logavdm,

Thanks for the input. I love having others contribute to the project. If you would like to help add features to the project, it will be more likely that they will make it. Otherwise, I try to wait for a few people to pull for specific features.

My thoughts on these features
1. I don't think turning the logger off for a specific component would be very usable. Instead, it would be valuable to create multiple instances of a logger (each having a unique config). Currently, there is only support for a signle instance. If multiple were supported, you could disable/enable the loggers individually.

1. can you please explain how this would be helpful? not sure I fully understand the use case you are trying to solve

1. This would be beneficial, and was requested before. A few guys tried to solve it, but weren't able to come up with a clean solution. You're more than welcome to take a stab at it if you'd like.

Thanks again for the feedback.

**Comment by dbfannin** [comment]
@logavdm, sorry it's taken so long for me to get around to this. as of 2.1.0, we now support creating a custom (or unique) logger instance. This would allow you to create loggers with their own config for any component/service that you would like to manages separately from the rest. 

Hope this helps!
