### ISSUE TITLE
Documentation Enhancement: Why should I use ngx-logger?

### ISSUE THREAD

**Issue by iexcept** [dbfannin/ngx-logger#45]
I think it would be nice to have a documentation section perhaps near the beginning of the README that answers common searcher's questions
- Why should I use it?
- Why did you guys start to develop a new library when angular2-logging exists?
- And in what situations ngx is better than angular2?

**Comment by dbfannin** [comment]
@iexcept, thanks for the interest in the logger. I'm trying to get a better idea on how we can enhance our documentation, to make sure people can quickly see if the logger will work for them. 

I don't really like comparing NGX Logger to other angular libraries. All libraries on NPM (including NGX Logger) have people contributing their free time and energy to adding features, and keeping their libraries updated. I don't feel comfortable advising on which library should be used. Instead, I would like to focus more on doing a better job quickly / plainly describing the features supported by the library.

We have a short paragraph in the readme, right at the beginning that gives a short description of the logger. This can probably be improved. Are there things in particular that you would like to see immediately? Would it be more clear if it were organized differently? Maybe using bullet points instead of paragraph style?

**Comment by dbfannin** [comment]
@iexcept, Since I haven't heard back, I'm going to go ahead and close this issue. Please reach out again if there is anything else you need.
