### ISSUE TITLE
File name/line-numbers no longer show accurately 

### ISSUE THREAD

**Issue by bniedermeyer** [dbfannin/ngx-logger#69]
I recently upgraded my app to Angular 6 and ngx-logger 3.0.0-rc1. 

Unfortunately the logger no longer shows the file name/line number of the log - instead it shows `main.js:<line num>`. 

**Previous behavior**
```
2018-06-11T19:06:58.864Z DEBUG [demo.component.ts:155] loading api       ngx-logger.js:386
```  
**Current behavior**
```
2018-06-11T19:06:58.864Z DEBUG [main.js:2164] loading api       ngx-logger.js:386
```

**Comment by dbfannin** [comment]
@bniedermeyer, It's not that the file line number is inaccurate, but that they are no longer using the the js maps. if you pull up `main.js:<line num>` in your browser, you'll see the line where the call to the logger was made. It's just showing the JS instead of the TS.

Since no changes in the logger were made around this, I believe it has something to do with how the maps are being generated in the latest version of angular. I don't believe it has anything to do with NGX Logger itself, but I'll have to do some research to confirm.

**Comment by jkossis** [comment]
Experiencing the same issue, any insight? Tried to scour some of the release notes, but nothing was mentioned from the Angular team on this...

**Comment by JavierFuentes** [comment]
I just updated the version to the latest available (**3.0.4**) and sadly view the problem persists... 

Curiously, **console.log does correctly indicate the line and my Typescript file instead of main.js**... 

I'm afraid that a logger that has stopped doing his work is not very useful, isn't it?

**Comment by bniedermeyer** [comment]
@JavierFuentes I wouldn't say that the logger has completely stopped doing its work. We still get access to things like logging to server which is still pretty useful in our use case. As a temporary work around we started including the file name in our log entries so we can at least have an idea of where the logger entry is being created.

**Comment by dbfannin** [comment]
@JavierFuentes, If you're going to comment, please try to stay constructive and positive. There is no need for negative comments. The people that support this project are sacrificing time and energy to provide you with a service at no cost to you, and they get no benefit from it themselves. Please be respectful.

**Comment by dbfannin** [comment]
Unfortunately, I haven't yet figured out why it is showing the compiled JavaScript filename:lineNumber instead of the typescript fileName:lineNumber. I haven't yet been able to spend much time looking into this, and would appreciate anyone's help it figuring out the issue. 

Thanks all!

**Comment by JavierFuentes** [comment]
@dbfannin, I'm sorry... I appreciate your work and efforts.

I'm not an expert and can't help you, but if console.log() works ok, I wonder if it would not be possible to use it in your code as a workaround even if it means losing the coloring of the text... my actual use case is simple because a don't need to logging at server side...

I apologize if I'm saying something meaningless.

**Comment by dbfannin** [comment]
@JavierFuentes, no worries. We do use console.log to log to the console. But, when the call to console.log() gets made, it is inside of the project file, not the file where logger.error() was called. So it would always show the filename:lineNumber where console.log was called within the logger. We get around this be throwing and catching an error in the logger, and tracing the stack to find where the call to the logger was made. and print that out. This printed the location of the typescript prior to upgrading to angular 6, but now prints the JS line number and name.

No need to apologize for "saying something meaningless" we're all learning here, and we learn faster as a community!

**Comment by JavierFuentes** [comment]
Hi @dbfannin , I just updated to version **3.0.5** and and I see that ngx-logger now gives much more verbose information in which it seems that my Typescript file name is included... I hope the final solution is closer... thanks in advance.

![image](https://user-images.githubusercontent.com/5801847/42133408-f914da0e-7d29-11e8-98c1-20224d291c42.png)

**Comment by gauavpareek014** [comment]
I am currently handling this by sending additional parameter of ts file name in trace function to the server side.  Waiting for this fix. Thanks!

**Comment by silentsnooc** [comment]
Any updates on this? The logger is not really helpful if file and line number are not correct .. :/

**Comment by reza-iranmanesh** [comment]
Is there any update on this? Current behavior makes console logs look ugly and hard to find out what's going on in one glance.

**Comment by Sidonet** [comment]
Hello,

is there any news? 
Due this bug have a lot of troubles...

**Comment by zeevkatz** [comment]
After I spent some time to find out what makes the logger to print the complied file name and row number I think it probably related to the JSON stringify that used in ‘prepareMessage׳ function. I tried to log message with ’console.error’ after JSON stringify and it's looks the same.

**Comment by basarawu66** [comment]
hello , when i use " npm run demo --  **--eval-source-map** "
, I can see log like " 2018-11-08T08:12:39.360Z INFO [app.component.ts?:35] [app.component]=>onInit"

**Comment by mviton** [comment]
Hi I just updated to version 3.3.6, when I use "ng serve app-test --evalSourceMap=true", the logger print the file and line correct
"2018-11-08T22:43:16.008Z INFO [dashboard-home.component.ts?:35] DashboardHomeComponent init"

**Comment by lppedd** [comment]
@mviton I'm not an Angular guy at all. Do you think using `evalSourceMap` is the definitive solution or just a workaround?

**Comment by mviton** [comment]
I'm not sure, the Angular documentation say that ng param
"--evalSourceMap=true|false     Output in-file eval sourcemaps.", I don't
know who affect this param in transpilation process.
It's possible that using this option param, all trace logs have file name
and numbre correct. But I haven't enough time to test it.

**Comment by bniedermeyer** [comment]
It may be a good workaround for development. I'm not sure how well this would work in production though. I feel a bit uneasy with shipping my source maps with production code.

**Comment by ampled** [comment]
I'm having a look at this library and toyed around with `getCallerDetails` and found something interesting:

If the caller exists in a file/module that somehow references the webpack environment-variable `module` the `getCallerDetails` function points to the correct file name and line number (by ts output anyway), but without a reference to `module` it gets `main.ts 45465` (it's a large project)

Note: I'm rolling a manual webpack config and the webpack dev server config has devtool: 'cheap-eval-source-map'

**Comment by ferinoc** [comment]
I tried to peace of code from this blog:
https://robferguson.org/blog/2017/09/09/a-simple-logging-service-for-angular-4/

and it looks that line number is working fine:
![image](https://user-images.githubusercontent.com/1408155/49223635-9651cd00-f3df-11e8-9bdc-4c3ea9f14559.png)

may be the  ngx-logger needs to be change like code from the blog?

`console.info.bind(console);`

**Comment by dbfannin** [comment]
@ferinoc, You're right. It is unfortunately a different approach. The reason it works for their logger, is that it is only returning the console method, and not doing any of other things that NGX Logger is doing, such as, log monitoring and server side logging. Otherwise, it would totally work. Thanks for the link to the blog though! It was an enjoyable read!

**Comment by hellerbarde** [comment]
what's the status on this? I have not even quite understood what changed to break this. How can we help?

**Comment by dbfannin** [comment]
@hellerbarde, there wasn't a change in the logger that broke this. Angular changed how it compiles. BUT, we still have a solution here. It's is to set `vendorSourceMap: true`.

https://blog.angular.io/?gi=b90fe360d2ea It is a valid option for serve and build. I would suggest setting it to false for your production build.

**Comment by dbfannin** [comment]
BTW. the `vendorSourceMap` flag doesn't seem to work for my angular 6 applications, but it does work for my angular 7 applications. Anyone else able to verify?

**Comment by ghiscoding** [comment]
@dbfannin 
I'm on Angular 7 and I do see the vendor maps, I don't have any Angular 6 so I can't answer for that one.

**Comment by TeXnicians** [comment]
@dbfannin `vendorSourceMap` doesn't seem to work for my Angular 7 applications. But `evalSourceMap` still work.

**Comment by dbfannin** [comment]
Thanks for the update @ghiscoding and @TeXnicians!

**Comment by rs200x** [comment]
@dbfannin `vendorSourceMap ` and `evalSourceMap` are marked as deprecated!
How do I get the source file name with the available parameters?
`--sourceMap=true` is not working

**Comment by greenwenny** [comment]
Same issue on Angular 7.2.x and evalSourceMap doesn't work. Any updates on this or time estimation for solution?

**Comment by Zenguro** [comment]
Still an issue. Using Angular 7.2.x.
None of the options stated here seem to work. 
I'm currently polluting logging text with class and method prefixes.
Already thinking about writing a wrapper class that must be configured in every constructor of a class where the logger will be used. (like Log4J in Java, where you have to set the class prefix for the logger yourself)

Having the correct filename and line numbers really help, since you can just click on the line reference in dev tools and jump right into the source code at the right position.

**Comment by jbarrett732** [comment]
I believe that this is an issue with angular 6 and webpack configuration. There is no need for evalSourceMap option since the map files are generated correctly. The browser is just not converting the transpile position back to source position. If you perform the conversion yourself using the source map, the correct source position is obtained. I added this solution to a forked branch (https://github.com/jbarrett732/ngx-logger) and submitted a pull request. 
An alternative to this solution would be to use a custom webpack config in your angular application, but that would require you to modify your angular cli build environment

**Comment by dbfannin** [comment]
shout out to @jbarrett732 for putting in the time and effort to figure out how to manually pull in and parse source maps. This should now work by adding the flag **enableSourceMaps: true** to your NGX Logger Config!

This is fixed in **ngx-logger@3.4.1**

**Comment by ghiscoding** [comment]
@dbfannin 
Question, do we also need to enable the source map in `angular.json` as well or does that work independently?

**Comment by dbfannin** [comment]
@ghiscoding, it relys on the source maps existing, so yes, sourceMap: true is necessary in your angular.json. The change here is to manually pull in and parse the source map to find the correct file name and number.

**Comment by lppedd** [comment]
@ghiscoding @dbfannin note that `--sourceMap` is deprecated. See my answer here https://stackoverflow.com/a/56669585/1392277

**Comment by ghiscoding** [comment]
@lppedd 
Thanks, that is a good point, I forgot that it was being deprecated, I used it because it was a short term fix at the time but now we have an official fix... Sweet!!
Thanks for pointing this out :)

@dbfannin
It might be useful to see a comment in your README, to note Angular source map needs to be enabled for this to work. ... basically, your answer to my previous question ;)

Thanks for the good work 👍

**Comment by dbfannin** [comment]
@ghiscoding, Great Feedback! I'll add that to the readme.

**Comment by tomanovy** [comment]
I just tested on Angular 9.0.0-rc.3
as adviced here [https://stackoverflow.com/a/56669585/1392277](https://stackoverflow.com/a/56669585/1392277)
but still getting main.js in logs
So on 9.0 only works with --evalSourceMap=true for now.

Anyone any ideas please?
Or someone more lucky on 9.0?

**Comment by tomanovy** [comment]
> I just tested on Angular 9.0.0-rc.3
> as adviced here https://stackoverflow.com/a/56669585/1392277
> but still getting main.js in logs
> So on 9.0 only works with --evalSourceMap=true for now.
> 
> Anyone any ideas please?
> Or someone more lucky on 9.0?

Looks like I found a solution to make [this](https://stackoverflow.com/a/56669585/1392277) work

      loggerConfig: {
        level: environment.production ? NgxLoggerLevel.WARN : NgxLoggerLevel.DEBUG,
        // serverLoggingUrl: '/api/logs',
        // serverLogLevel: NgxLoggerLevel.OFF,
        enableSourceMaps: true, // <-- THIS IS REQUIRED, to make "line-numbers" work in SourceMap Object defition (without evalSourceMap)
        disableConsoleLogging: environment.production
      }
