### ISSUE TITLE
How to enable/disable logger in production environment.

### ISSUE THREAD

**Issue by pankajsri03** [dbfannin/ngx-logger#7]
I wish to know how to turn on and off logger based on production and development environment

**Comment by dbfannin** [comment]
@pankajsri03, in order to disable the logger, pass in "OFF" as the log level
`LoggerModule.forRoot({level: 'OFF'})`

When wanting to do this for production only, use your production configuration to set your log level to OFF while your dev configuration sets it to DEBUG (or whatever other level you desire).

**Comment by dsebastien** [comment]
@dbfannin can you share an example of how to do this? Naively I tried to do this as follows, but it failed apparently due to this issue: https://github.com/angular/angular/issues/14707

Here's what I've tried: 

```
const LOG_LEVEL: NgxLoggerLevel = isDevMode()? NgxLoggerLevel.DEBUG: NgxLoggerLevel.WARN;
...
imports: [
    LoggerModule.forRoot({level: LOG_LEVEL, serverLogLevel: NgxLoggerLevel.OFF}),
]
```
