### ISSUE TITLE
Use NGXLogger without Angular DI

### ISSUE THREAD

**Issue by aleksandar78** [dbfannin/ngx-logger#74]
Hi, 

I'm trying to use this library in our Angular project. You did a great job, IMHO. 

Our app uses ngrx/store and we need to log some logic inside our reducers. I can't figure it out how
to initialize NGXLogger on my own. As you probably know reducers are pure ts/js functions files, no framework dependency injection at all. 

Another question. How to get correct source file name and line number in the console output. 

Any advice would be appreciated.

Thanks

**Comment by dbfannin** [comment]
@aleksandar78, thanks for the interest in the logger! 

I'm not sure you want to instantiate the logger outside of angular's DI. There's a lot of risk that the logger updates it's dependencies and breaks your code, and just a big headache in new'ing everything up. 

The best solution might be to instantiate the logger using a class that supports Angular DI, and create a singleton that your non-angular files can use (either using the main logger or the custom logger, see the readme for details).

for example say in your app.component.ts

```
import {initLogger} from './tsLogger';

constructor(private logger: NGXLogger) {
        initLogger(logger);
}
```

tsLogger.ts
```
import {NGXLogger} from 'ngx-logger';

export let logger: NGXLogger;

export const initLogger = (newLogger: NGXLogger) => logger = newLogger;
```

then in any of the non-angular files you can just import the instance of NGXLogger.

```
import logger from './tsLogger';


export class MyClass{
    constructor() {}

    logSomething() {
        logger.error('something happened');
    }
}
```


Unfortunately with the release of angular 6 the `filename:lineNumber` has started referencing the transpiled JS file name and line number instead of the typescript map. We've done some research, but haven't been able figure it out just yet. As soon as we do, we'll update the logger with the fix.

I hope this helps!

**Comment by aleksandar78** [comment]
Thanks for replay. 

I'll try your solution for LoggerService initialization outside Angular DI.

**Comment by pedy711** [comment]
It has been 4 years since the last comment. Is there a better solution to this problem?

**Comment by Ayushi96** [comment]
How can I write Unit Tests for the utility funciton which makes use of this logger
