### ISSUE TITLE
Trace and Debug do not work in 3.0.5

### ISSUE THREAD

**Issue by mbeckenbach** [dbfannin/ngx-logger#77]
Hi, 

trace and debug only output data when chromes console log level is set to verbose in 3.0.5.
A downgrade to 3.0.4 solves that.

Best regards

**Comment by yildiraymeric** [comment]
Hi,

Prior to version 3.0.5, all logging was performed via only "console.log" function. But this is changed to using specific logger functions of the console object (console.debug, console.trace, console.info, console.error.. etc). (Please see #71) 

This allows developers to easily filter out console messages using browser's developer tools and also allows color rendering for log messages like "error". Only side affects is that Chrome is filtering out "trace" and "debug" messages by default, in which case developers should change the log level to "verbose" to see them.

So all log levels are working fine and logging messages to console but Chrome is filtering out some of them by default.

This is not an issue or bug, but expected behaviour.

**Comment by mbeckenbach** [comment]
I see. But this causes lots of console spam by chrome itself, which makes using the DEBUG Level almost useless for me.

**Comment by mbeckenbach** [comment]
By the way: 
Why is TRACE beeing shown when the Level is set to DEBUG?

**Comment by dbfannin** [comment]
@mbeckenbach, I'm not able to reproduce TRACE being shown when the level is set to DEBUG. can you please provide the code you are using in order to reproduce this issue?

**Comment by dbfannin** [comment]
Since I haven't heard back in over 2 weeks, I'm assuming this was an implementation issue and closing. If this is still an active issue, please re-open it. Thanks!
