### ISSUE TITLE
Additional data is output as two-dimensional array

### ISSUE THREAD

**Issue by javix** [dbfannin/ngx-logger#84]
I have the following implementation:

```
import { NGXLogger } from 'ngx-logger';

export interface LoggerInterface {
    debug( message: any, ...additional: any[] ): void;
    info( message: any, ...additional: any[] ): void;
    warn( message: any, ...additional: any[] ): void;
    error( message: any, ...additional: any[] ): void;
}

class NGXLoggerBridge implements LoggerInterface {

    private logger: NGXLogger;

    public constructor( logger: NGXLogger ) {
        this.logger = logger;
    }

    public debug( message: any, ...additional: any[] ): void {
        this.logger.debug( message, additional );
    }

    public info( message: any, ...additional: any[] ): void {
        this.logger.info( message, additional );
    }

    public warn( message: any, ...additional: any[] ): void {
        this.logger.warn( message, additional );
    }

    public error( message: any, ...additional: any[] ): void {
        this.logger.error( message, additional );
    }

}

export class Logger {

    private static logger: LoggerInterface;

    public static initLogger( logger: NGXLogger ): void {
        this.logger = new NGXLoggerBridge( logger );
    }

    public static debug( message: any, ...additional: any[] ): void {
        this.logger.debug( message, additional || null );
    }

    public static info( message: any, ...additional: any[] ): void {
        this.logger.info( message, additional || null );
    }

    public static warn( message: any, ...additional: any[] ): void {
        this.logger.warn( message, additional || null );
    }

    public static error( message: any, ...additional: any[] ): void {
        this.logger.error( message, additional || null );
    }
}
```
In the console, I see the following:
![image](https://user-images.githubusercontent.com/5870244/46131008-ed4df100-c23a-11e8-8d11-5218db28c08a.png)

I expect that if no additional data is given, no empty array will be printed.

**Comment by dbfannin** [comment]
@javix the spread operator `(...additional: any[])` takes all additional parameters passed to that function and adds them to an array named "additional". If there are not any additional params, the array still exists, but is empty.

in JavaScript/TypeScript || and && operators do not return booleans. They return the first value that is a truthy (or the last falsy) and the last value that is a truthy (or the first falsy). 

In your code `this.logger.error( message, additional || null );` or more specifically `additional || null` additional is an empty array `[]` empty arrays and empty objects are always truthies. since the || operator always returns the first truthy, the empty array will aways be passed into the logger method, and null will NEVER be passed in. 

To fix this, you will need to check the length of additional.
`this.logger.error( message, additional.length ? additional : null );` would work, or something similar. 

I hope this clears things up!

**Comment by dbfannin** [comment]
Closing this issue, since it is not an issue with the logger. If you have anymore questions, feel free to re-open it!
