### ISSUE TITLE
serverLoggingUrl

### ISSUE THREAD

**Issue by chinnarao** [dbfannin/ngx-logger#92]
this method is using httpclient. here is my problem, when i log using this method , it is showing loading spinning image/icon in my application ,the reason is i am using httpinterceptor for showing spinner , obviously your serverloggingurl method also using my interceptor for spinning , so if i log 100 messages to log using this method then the spinner is always displaying in my application. so the solution for now is i have to get out of your ngx-logger to avoid unnecessary background log spinning or i have to not to use my interceptor. 
So please advise sir , i am requesting to owner of the ngx-logger?. or my advise is, please use ajax or XMLHttpRequest for serverLoggingUrl

thanks in advance:

**Comment by MarkoSulamagi** [comment]
I can see 2 options here that you could do

1. You can add an exception to your interceptor so that spinner is not shown when the request endpoint is your logging endpoint (I suggest this one)

2. You can turn off default server logger and write your own custom service that will send the logs to server (with xmlhttprequest). You can do that with the recently added NGXLoggerMonitor.

Changing ngx-logger to not use HttpClient would be a bad idea for various reasons (usability, testability).

**Comment by dbfannin** [comment]
@chinnarao, If you want to keep the spinner logic in your interceptor, I agree with @MarkoSulamagi, and also think his option 1 is the best choice. I would suggest setting your logger url in your environment config files, and referencing the environment file when setting the logger config and in your interceptor. 

One other option you may want to consider, is to move the spinner visibility logic out of your interceptor. Most apps have some type of server communication that runs in the background that does not affect user interaction with the app (like the logger, keep alive services, etc). If you keep that logic in your interceptor, you have to come up with a whitelisting strategy, or some other way of knowing what URLs need to show the spinner. It's a convenience vs flexibility battle :)

Whatever you decide to do, I think you now have a few options. Good luck!

**Comment by chinnarao** [comment]
Thanks MarkoSulamagi and 
 Owner
dbfannin.

Great suggestions and great help, thanks for your time. i like MarkoSuamagi first option. apprecated sir.
