### ISSUE TITLE
Log level "log", what is it supposed to be used for ?

### ISSUE THREAD

**Issue by appsolutegeek** [dbfannin/ngx-logger#94]
Hi,

I have come across the other log levels. But what is "log" used for ?

Also, fatal doesn't exist ?

Thanks

**Comment by MarkoSulamagi** [comment]
@dbfannin can clarify, but my guess is that it's based on [Javascript console log](https://developer.mozilla.org/en-US/docs/Web/API/console) levels. The spec is quite vague on the difference of LOG and INFO and so they're considered pretty much the same in JS community. LOG is shorter then INFO :smile: 

 https://developer.mozilla.org/en-US/docs/Web/API/Console/info
https://developer.mozilla.org/en-US/docs/Web/API/Console/log
```
**Console.info()**
Informative logging of information. You may use string substitution and additional arguments with this method.

**Console.log()**
For general output of logging information. You may use string substitution and additional arguments with this method.
```

**Comment by appsolutegeek** [comment]
Ok, great, thanks for the quick response. I assumed it was for something similar to INFO. Thanks

**Comment by dbfannin** [comment]
@MarkoSulamagi, as always, thank you for your explanation and quick response! The only thing I will add is more about its use case with NGX Logger. Sometimes there is a need for general log statements to be more or less verbose. So having both info and log gives the flexibility to disable the more verbose logging while still keeping general log statements enabled. I do not personally use both, but there are subscribers to NGX Logger that do.

As far as for FATAL. I'm actually pretty surprised no one has requested it up until this point. FATAL vs ERROR have basically the same relationship as INFO vs LOG. FATAL and ERROR are both errors, one is just classified as a more extreme, non-recoverable error. 

Since not having fatal as a supported log level seemed like a gap, I've added FATAL as an option in ngx-logger@3.3.5.
